export const moods = [
  { label: "Abstract", value: "abstract" },
  { label: "Angry", value: "angry" },
  { label: "Anxious", value: "anxious" },
  { label: "Calm", value: "calm" },
  { label: "Confused", value: "confused" },
  { label: "Curious", value: "curious" },
  { label: "Detached", value: "detached" },
  { label: "Elated", value: "elated" },
  { label: "Embarrassed", value: "embarrassed" },
  { label: "Empowered", value: "empowered" },
  { label: "Excited", value: "excited" },
  { label: "Floaty", value: "floaty" },
  { label: "Frustrated", value: "frustrated" },
  { label: "Grateful", value: "grateful" },
  { label: "Hopeful", value: "hopeful" },
  { label: "Hopeless", value: "hopeless" },
  { label: "Indecisive", value: "indecisive" },
  { label: "Indifferent", value: "indifferent" },
  { label: "Inspired", value: "inspired" },
  { label: "Joyful", value: "joyful" },
  { label: "Lonely", value: "lonely" },
  { label: "Lucid", value: "lucid" },
  { label: "Nightmarish", value: "nightmarish" },
  { label: "Observant", value: "observant" },
  { label: "Peaceful", value: "peaceful" },
  { label: "Reflective", value: "reflective" },
  { label: "Sad", value: "sad" },
  { label: "Surreal", value: "surreal" },
  { label: "Trippy", value: "trippy" },
  { label: "Vivid", value: "vivid" },
];

export const people = [
  { label: "Alone", value: "alone" },
  { label: "Boss", value: "boss" },
  { label: "Celebrity", value: "celebrity" },
  { label: "Child", value: "child" },
  { label: "Enemy", value: "enemy" },
  { label: "Family", value: "family" },
  { label: "Friend", value: "friend" },
  { label: "Partner", value: "partner" },
  { label: "Spiritual Figure", value: "spiritual_figure" },
  { label: "Stranger", value: "stranger" },
  { label: "Teacher", value: "teacher" },
];

export const places = [
  { label: "City", value: "city" },
  { label: "Desert", value: "desert" },
  { label: "Forest", value: "forest" },
  { label: "Home", value: "home" },
  { label: "Mountain", value: "mountain" },
  { label: "Nowhere", value: "nowhere" },
  { label: "Ocean", value: "ocean" },
  { label: "School", value: "school" },
  { label: "Space", value: "space" },
  { label: "Temple", value: "temple" },
  { label: "Workplace", value: "workplace" },
];

export const objects = [
  { label: "Animal", value: "animal" },
  { label: "Book", value: "book" },
  { label: "Car", value: "car" },
  { label: "Clock", value: "clock" },
  { label: "Clothing", value: "clothing" },
  { label: "Door", value: "door" },
  { label: "Key", value: "key" },
  { label: "Mirror", value: "mirror" },
  { label: "Nothing", value: "nothing" },
  { label: "Phone", value: "phone" },
  { label: "Weapon", value: "weapon" },
];
